"""Reliability runner: model-level event-level evaluation from SAVED prediction arrays only.

Never retrains, never generates predictions, never touches final_test.npz.
It scans experiments/results/final_comparison/ for saved prediction artifacts (*.npz that
contain `y_true` and `y_pred`). If none exist, model-level evaluation is reported as
unavailable and the report says so. Existing experiment metrics are read-only here.
"""
import json
from datetime import date

import numpy as np

from src import config as C
from src.reliability import ReliabilityEngine

FINAL_DIR = C.ROOT / "experiments" / "results" / "final_comparison"
OUT_DIR = C.ROOT / "experiments" / "results" / "reliability"
REPORT = OUT_DIR / "reliability_report.md"


def find_prediction_artifacts(directory=FINAL_DIR):
    """Saved prediction arrays: *.npz files (any depth) with y_true and y_pred. final_test files are excluded."""
    found = []
    if not directory.exists():
        return found
    for p in sorted(directory.rglob("*.npz")):
        if "final_test" in p.name.lower():
            continue
        with np.load(p, allow_pickle=False) as z:
            if "y_true" in z.files and "y_pred" in z.files:
                found.append(p)
    return found


def _fmt(v, nd=4):
    return "n/a" if v is None else (f"{v:.{nd}f}" if isinstance(v, float) else str(v))


def build_report(results, directory=FINAL_DIR):
    rel_dir = directory.relative_to(C.ROOT).as_posix()
    available = bool(results)
    L = ["# Reliability Report", "", f"_Generated by `src/reliability_runner.py` on {date.today().isoformat()}._", "",
         "## 1. Reliability Engine implementation status", "",
         "**Implemented and unit-tested.** `src/reliability.py` provides:", "",
         "- `find_contiguous_segments(binary_sequence)` - contiguous `(start, end)` runs (end inclusive); empty input returns `[]`.",
         "- `ReliabilityEngine(y_true, y_pred).evaluate()` - true / detected / missed segment counts, detection coverage, "
         "per-segment detection delay, predicted segments, false-alarm segments and `false_alarm_segment_rate`.", "",
         "Detection logic: a predicted segment detects a true segment if they overlap; delay = first overlapping predicted "
         "sample - true start; a true segment with no overlapping predicted segment is missed; a predicted segment that "
         "overlaps no true segment is a false-alarm segment. Undefined ratios (zero denominator) are reported as `None`/n/a.", "",
         "Tests: `tests/test_reliability.py` (segment extraction, perfect detection, delay, missed segment, false-alarm "
         "segment, no-anomaly, no-prediction, length mismatch, plus a few extra edge cases).", "",
         "## 2. Model-level reliability evaluation status", ""]
    if available:
        L += ["**Available** for the saved prediction artifacts below.", "",
              "| Artifact | True seg | Detected | Missed | Coverage | Mean delay | Pred seg | FA seg | FA segment rate |",
              "|---|---|---|---|---|---|---|---|---|"]
        for name, r in results.items():
            L.append(f"| {name} | {r['true_segments']} | {r['detected_segments']} | {r['missed_segments']} | "
                     f"{_fmt(r['detection_coverage'])} | {_fmt(r['mean_detection_delay'], 2)} | {r['predicted_segments']} | "
                     f"{r['false_alarm_segments']} | {_fmt(r['false_alarm_segment_rate'])} |")
        L.append("")
    else:
        L += ["**UNAVAILABLE.** Model-level quantitative reliability evaluation with the new Reliability Engine has **not** "
              "been performed. No numbers are reported for any model.", ""]
    L += ["## 3. Missing prediction-artifact limitation", ""]
    if available:
        L += ["Only the artifacts listed above were evaluated; models without a saved artifact are not covered.", ""]
    else:
        L += [f"The runner searched `{rel_dir}/` (recursively) for saved prediction arrays (`*.npz` containing `y_true` and "
              "`y_pred`) and found none. Only model checkpoints (`best_model.pt`), `metrics.json` files and comparison "
              "tables are stored, not per-sample validation predictions or labels. `val_predictions.npz` is not assumed to exist.", "",
              "Per project constraints, models were **not** retrained, no new predictions were generated, and "
              "`data/processed/machine-1-1/final_test.npz` was **not** loaded, so the arrays were not recreated. "
              "Existing experiment metrics were not modified. Note that the `reliability` blocks already inside the "
              "experiment `metrics.json` files come from the legacy helper `reliability_stats`; they were not produced by "
              "the new engine and are not re-evaluated here.", "",
              "To enable this evaluation later, save validation `y_true` / `y_pred` per model as `.npz` files under the "
              "final-comparison directory (an explicit, separately approved step) and re-run the runner.", ""]
    L += ["## 4. Event-level false-alarm segment-rate definition", "",
          "```", "false_alarm_segment_rate = false_alarm_segments / predicted_segments", "```", "",
          "- `predicted_segments`: contiguous runs of predicted anomalies.",
          "- `false_alarm_segments`: predicted segments that overlap **no** true anomaly segment.",
          "- This is an **event-level segment proportion**. It is **not** the sample-level false positive rate "
          "(FP / (FP + TN)), which is what the `false_alarm_rate` field in the existing `metrics.json` files reports. "
          "The two measure different things and must not be compared or substituted.",
          "- If there are no predicted segments the rate is undefined and reported as n/a.", ""]
    return "\n".join(L)


def run_reliability(directory=FINAL_DIR, report_path=REPORT):
    results = {}
    for p in find_prediction_artifacts(directory):
        with np.load(p, allow_pickle=False) as z:
            results[p.relative_to(directory).as_posix()] = ReliabilityEngine(z["y_true"], z["y_pred"]).evaluate()
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(build_report(results, directory), encoding="utf-8")
    return {"model_level_available": bool(results), "artifacts_evaluated": list(results), "report": str(report_path)}
